### ISSUE TITLE
feature: Notification Badge on System Tray Icon

### ISSUE THREAD

**Issue by 8227846265** [webcatalog/webcatalog-classic#1502]
# Feature Request
**Specifications:**
- WebCatalog Version: 36.3.2 (x64)
- OS (macOS, Windows, Linux): Windows 10

**Description:**
Hi, I would like to suggest a feature to add an option on the Settings to include the Notification Badge on the System Tray. Looking at Gmail, it seems the Notification Badge turned on only works when Gmail is on the taskbar but when closed to System Tray, there's no notification badge.

This creates a chance for the user to missed new emails until they opened the Gmail app or check the notification bar.

**Additional Context**
If `Notification Badge on System Tray` is not possible. 

`Close Application to Taskbar` would be a nice alternative. The primary goal of this enhancement is to ensure the user is able to get the Notification Badge working to ensure the user gets informed they have a new email.

Relying on the Notification Center to inform the user that there are new emails is unreliable since the Notification Center can include notifications from other apps aside from the apps installed through WebCatalog.

**Comment by fakhamatia** [comment]
Any progress?
I install PortMaster today, it uses Electron and has a badge.
![image](https://user-images.githubusercontent.com/20030910/150677366-e8776b83-c4a8-417d-9f5e-9f6aa3214985.png)

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
