### ISSUE TITLE
bug: CMD Opens At Every WebCatalog App Opening

### ISSUE THREAD

**Issue by 8227846265** [webcatalog/webcatalog-classic#1578]
# Bug Report
**Specifications:**
- WebCatalog Version: v40.2.0 (x64)
- Neutron Version:
- OS (macOS, Windows, Linux): Windows 11

**Description:**
When opening WebCatalog apps, CMD opens. It's more prominent when you have apps that open on startup. Not sure why it opens CMD every single time.

**Steps to Reproduce:**
Open an installed WebCatalog app and CMD will open before the app fully loads.

**Comment by maxoku** [comment]
It also opens with a sub window like preferences.

**Comment by quanglam2807** [comment]
This bug is fixed in the latest version.
